language: node_js
node_js: 
    - "7.0"

script:
  - echo "Deploying!"
  - npm install
  - npm start

install:
  - npm install -g firebase-tools

after_success:
  - firebase deploy --token $FIREBASE_TOKEN