language: node_js
node_js: 
    - "6.0"

script:
  - echo "Deploying!"
  - npm install -g npm@latest
  - rm -rf node_modules
  - npm run build

install:
  - npm install -g firebase-tools

after_success:
  - firebase deploy --token $FIREBASE_TOKEN